"""Paste

Revision ID: 2596634bc1e3
Revises: 4e2d0a01ffb8
Create Date: 2026-06-16 16:23:34.189046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2596634bc1e3'
down_revision: Union[str, Sequence[str], None] = '4e2d0a01ffb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursions', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('excursions', sa.Column('distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursions', 'distance')
    op.drop_column('excursions', 'duration')
    # ### end Alembic commands ###
