"""Add new users and points fields, favorites table added

Revision ID: 81bb5b3f2195
Revises: 337b15e67432
Create Date: 2026-03-25 12:54:04.034306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bb5b3f2195'
down_revision: Union[str, Sequence[str], None] = '337b15e67432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_excursions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'excursion_id')
    )
    op.add_column('points', sa.Column('excursion_id', sa.Integer(), nullable=True))
    op.alter_column('points', 'radius_meters',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'points', 'excursions', ['excursion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.alter_column('points', 'radius_meters',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('points', 'excursion_id')
    op.drop_table('user_favorite_excursions')
    # ### end Alembic commands ###
