"""Renew tables 4

Revision ID: 8214d9fd3dc9
Revises: 02f72c357d0e
Create Date: 2026-04-25 10:38:13.515137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8214d9fd3dc9'
down_revision: Union[str, Sequence[str], None] = '02f72c357d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'position')
    # ### end Alembic commands ###
