"""Renew tables

Revision ID: a7247c134727
Revises: ce21ef2a0f98
Create Date: 2026-04-25 10:21:43.020076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7247c134727'
down_revision: Union[str, Sequence[str], None] = 'ce21ef2a0f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursion_media_link', 'is_cover')
    op.drop_column('point_media_link', 'order_index')
    op.drop_column('points', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('point_media_link', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('excursion_media_link', sa.Column('is_cover', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
