"""Added distance and duration in Excursion table 2

Revision ID: b22e63723699
Revises: cbd5c03d0b75
Create Date: 2026-06-16 16:17:58.138483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22e63723699'
down_revision: Union[str, Sequence[str], None] = 'cbd5c03d0b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
