"""Deleted distance and duration

Revision ID: c141f78bbe77
Revises: b22e63723699
Create Date: 2026-06-16 16:18:37.961977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c141f78bbe77'
down_revision: Union[str, Sequence[str], None] = 'b22e63723699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursions', 'duration')
    op.drop_column('excursions', 'distance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursions', sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('excursions', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
