"""Refactor points and media with association tables

Revision ID: c322e3277aa6
Revises: e09bf31f56f8
Create Date: 2026-04-01 09:48:29.983334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c322e3277aa6'
down_revision: Union[str, Sequence[str], None] = 'e09bf31f56f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'AUDIO', name='media_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_table('excursion_media_link',
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('excursion_id', 'media_id')
    )
    op.create_table('point_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_content_id'), 'point_content', ['id'], unique=False)
    op.create_table('point_media_link',
    sa.Column('point_content_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_content_id'], ['point_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_content_id', 'media_id')
    )
    op.drop_column('points', 'image_url')
    op.drop_column('points', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('point_media_link')
    op.drop_index(op.f('ix_point_content_id'), table_name='point_content')
    op.drop_table('point_content')
    op.drop_table('excursion_media_link')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
