"""Renew point table

Revision ID: ce21ef2a0f98
Revises: de6748c47db6
Create Date: 2026-04-16 16:19:00.384691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce21ef2a0f98'
down_revision: Union[str, Sequence[str], None] = 'de6748c47db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_content', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('point_content', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('points', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('points', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('points', 'text')
    op.drop_column('points', 'title')
    op.drop_column('points', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('points', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('points', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('point_content', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('point_content', 'address')
    # ### end Alembic commands ###
