"""Added status in Excursion Table

Revision ID: d883b9b52122
Revises: 0c210110c2b5
Create Date: 2026-05-23 13:26:47.439098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd883b9b52122'
down_revision: Union[str, Sequence[str], None] = '0c210110c2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursions',
                 sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='excursionstatus'), nullable=True))

    # Шаг 2: Проставляем всем существующим записям дефолтный статус 'DRAFT'
    op.execute("UPDATE excursions SET status = 'DRAFT' WHERE status IS NULL")

    # Шаг 3: Делаем колонку обязательной (NOT NULL)
    op.alter_column('excursions', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursions', 'status')
    # ### end Alembic commands ###
